version: '3.4'

services:
  client:
    image: ${DOCKER_REGISTRY-}client
    build:
      context: .
      dockerfile: Client/Dockerfile

  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile

  is4:
    image: ${DOCKER_REGISTRY-}is4
    build:
      context: .
      dockerfile: IdentityProvider/Dockerfile
    depends_on:
      - "db"
 
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: P@ssword!
      POSTGRES_DB: IS4Database 

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080